spring.application.name=caseapp
# Datasource
spring.datasource.url=jdbc:mysql://localhost:3306/casetrackerdb?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=63-2239595a47l

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret
jwt.secret=RIMISayoTh261W62jnMxxE3g2iTw3NgLM5FP0EAQ4a3iB4PgD/MlLEH5dSJKSZg1YCPPTa6NqwmEAYnvcEKYPA==
jwt.expirationMs=86400000


# Mail config (example with Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nyandorolyn@gmail.com
spring.mail.password=ubwforjpahzijfal
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Server port
server.port=8080

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

